# Generated by Django 5.1.7 on 2025-03-29 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_cateogry_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cateogry',
            new_name='categories',
        ),
    ]
