# Generated by Django 5.1.7 on 2025-03-29 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_cateogry_post_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cateogry',
            new_name='Category',
        ),
    ]
