# Generated by Django 5.1.7 on 2025-03-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
